#!/bin/bash

#
# Copyright 2012-2015 Johns Hopkins University HLTCOE. All rights reserved.
# This software is released under the 2-clause BSD license.
# See LICENSE in the project root directory.
#

#
# THIS SCRIPT SHOULD ONLY BE RUN BY PACKAGE MAINTAINERS.
# If you are not a package maintainer, then you can safely ignore this
# script - all the information you need to use the Concrete-Python
# library can be found in README.md
#
# The Concrete-Thrift repository contains the .thrift definition
# files, but not the Python classes generated by the Thrift compiler.
# This repository (Concrete-Python) contains the Thrift-generated
# Python classes, but not the .thrift definition files.
#
# This script should be run whenever the .thrift definition files in the
# Concrete-Thrift repository are changed.
#


DEFAULT_CONCRETE_THRIFT_DIR=../concrete/thrift
DEFAULT_OUTPUT_DIR=concrete

print_usage() {
    echo "Usage: $0 [--raw] [--output-dir OUTPUT-DIR] [CONCRETE-THRIFT-DIR]"
    echo "  --raw:  Just generate classes from thrift definitions"
    echo "          (do not apply our modifications)"
    echo "  --output-dir OUTPUT-DIR:  Write output to OUTPUT_DIR instead of"
    echo "                            $DEFAULT_OUTPUT_DIR"
}


#
# Parse command-line arguments
#

concrete_thrift_dir="$DEFAULT_CONCRETE_THRIFT_DIR"
raw=false
output_dir="$DEFAULT_OUTPUT_DIR"

num_pos_args=0

while [ $# -gt 0 ]
do
    case "$1" in
        --raw)
            raw=true
            ;;
        --output-dir)
            shift
            output_dir="$1"
            ;;
        -h)
            print_usage
            exit 0
            ;;
        --help)
            print_usage
            exit 0
            ;;
        *)
            if [ $num_pos_args -eq 0 ]
            then
                concrete_thrift_dir="$1"
                num_pos_args=$(($num_pos_args + 1))
            else
                print_usage >&2
                exit 1
            fi
            ;;
    esac
    shift
done


set -e

echo 'Generating Python classes from thrift definitions...'
rm -rf gen-py
for t in `find $concrete_thrift_dir -name '*.thrift'`
do
    thrift --gen py:coding=utf-8 $t
done

echo 'Deleting generated files we do not want...'
rm -f gen-py/concrete/__init__.py

echo "Copying newly-generated classes to $output_dir/..."
cp -a gen-py/concrete/* "$output_dir/"

if ! $raw
then
    echo 'Applying our modifications to generated classes...'
    for p in patches/*.patch
    do
        patch -p1 < $p
    done
fi

echo 'Done.'
