#!/bin/bash

#
# Copyright 2012-2015 Johns Hopkins University HLTCOE. All rights reserved.
# This software is released under the 2-clause BSD license.
# See LICENSE in the project root directory.
#

#
# THIS SCRIPT SHOULD ONLY BE RUN BY PACKAGE MAINTAINERS.
# If you are not a package maintainer, then you can safely ignore this
# script - all the information you need to use the Concrete-Python
# library can be found in README.md
#
# The Concrete-Thrift repository contains the .thrift definition
# files, but not the Python classes generated by the Thrift compiler.
# This repository (Concrete-Python) contains the Thrift-generated
# Python classes, but not the .thrift definition files.
#
# This script should be run whenever the .thrift definition files in the
# Concrete-Thrift repository are changed.
#


DEFAULT_OUTPUT_DIR=concrete

print_usage() {
    echo "Usage: $0 [--raw] CONCRETE-THRIFT-PATH"
    echo "  --raw:  Just generate classes from thrift definitions"
    echo "          (do not apply our modifications)"
    echo "  --output-dir OUTPUT-DIR:  Write output to OUTPUT_DIR instead of"
    echo "                            $DEFAULT_OUTPUT_DIR"
}


#
# Parse command-line arguments
#

raw=false
output_dir="$DEFAULT_OUTPUT_DIR"

while [ $# -gt 0 ]
do
    case "$1" in
        --raw)
            raw=true
            ;;
        --output-dir)
            shift
            output_dir="$1"
            ;;
        -h)
            print_usage
            exit 0
            ;;
        --help)
            print_usage
            exit 0
            ;;
        *)
            if [ -z "$concrete_thrift_path" ]
            then
                concrete_thrift_path="$1"
            else
                print_usage >&2
                exit 1
            fi
            ;;
    esac
    shift
done

if [ -z "$concrete_thrift_path" ]
then
    print_usage >&2
    exit 1
fi


set -e

echo 'Generating Python classes from thrift definitions...'
rm -rf gen-py
for P in `find $concrete_thrift_path -name '*.thrift'`
do
    thrift --gen py:new_style,utf8strings,coding=utf-8 $P
done

echo 'Deleting generated files we do not want...'
rm -f gen-py/concrete/__init__.py

echo "Copying newly-generated classes to $output_dir/..."
cp -a gen-py/concrete/* "$output_dir/"

if ! $raw
then
    echo 'Applying our modifications to generated classes...'
    for P in patches/*.patch
    do
        patch -d "$output_dir" -p1 < $P
    done
fi

echo 'Done.'
