#!/bin/bash

# Path to Concrete repo that contains the Python classes generated by
# the Thrift compiler
CONCRETE_PATH="../concrete-craig"

rm setup.py
rm -rf concrete

cp -a ${CONCRETE_PATH}/python/setup.py .
cp -a ${CONCRETE_PATH}/python/concrete/ concrete/
